config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :campaigns
  root "campaigns#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/campaign.rb
class Campaign < ApplicationRecord
  belongs_to :user

  has_attached_file :image, :styles => { :medium => "300x300>" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ApplicationRecord
  has_many :campaigns

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
  before_action :find_campaign, only: [:show, :edit, :update, :destroy]

  def index
    @campaigns = Campaign.all.order("created_at DESC")
  end

  def show
  end

  def new
    # @campaign = Campaign.new
    @campaign = current_user.campaigns.build
  end

  def create
    # @campaign = Campaign.new(campaign_params)
    @campaign = current_user.campaigns.build(campaign_params)
    if @campaign.save
        redirect_to @campaign, notice: "Yessss! It was posted"
    else
      render "new"
    end
  end

  def edit
  end

  def update
    if @campaign.update(campaign_params)
      redirect_to @campaign, notice: "Congrats! Campaign was updated!"
    else
      render 'edit'
    end
  end

  def destroy
    @campaign.destroy
    redirect_to root_path
  end

  private

  def campaign_params
    params.require(:campaign).permit(:title, :description, :image)
  end

  def find_campaign
    @campaign = Campaign.find(params[:id])
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/campaigns_helper.rb
module CampaignsHelper
end

app/views/campaigns/_form.html.erb
<%= simple_form_for @campaign do |c| %>
  <%# <div id="errors">
    <h2>
      <%= pluralize(@campaigns.errors.count, "error") %>
        <%# <ul>
          <% @campaigns.errors.full_message.each do |msg| %>
             <%# <li>
            <%= msg %>
            <%# </li>
          <% end  %>
         <%# </ul>
    </h2>
  </div> %>

  <div class="form-group">
    <%= c.input :title, input_html: { class: 'form-control'} %>
    <%= c.input :description, input_html: { class: 'form-control'} %>
    <%= c.input :image, input_html: { class: 'form-control'} %>
    <%= c.button :submit, class: 'btn btn-info' %>
  </div>
<% end %>

app/views/campaigns/edit.html.erb
<div id="edit_page" class="col-md-8 col-md-offset-2">
  <div class="row">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h1>Fix campagnes</h1>
      </div>
      <div class="panel-body">
        <div class="current_image">
          <strong>Rigth now</strong>
          <%= image_tag @campaign.image.url(:medium) %>
        </div>
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

<%= link_to 'Cancel', campaign_path %>

app/views/campaigns/index.html.erb
<h1>Campagne AD CREW</h1>
<div class="col-md-6 col-md-offset-3">
  <div id="campaigns" class="transitions-enabled">
    <% @campaigns.each do |campaign| %>
      <div class="box panel panel-default">
        <%= link_to (image_tag campaign.image.url), campaign %>
        <h2>
          <%= link_to campaign.title, campaign %>
        </h2>
      </div>
    <% end %>
  </div>
</div>

<%# <%= link_to "Gram it", new_campaign_path %>

app/views/campaigns/new.html.erb
<div class="col-md-8 col-md-offset-2">
  <div class="row">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h1>Post campagne</h1>
      </div>
      <div class="panel-body">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

<%= link_to "back", root_path%>

app/views/campaigns/show.html.erb
<div class="campaing_show row">
  <div class="col-md-6 col-md-offset-3">
    <div class="panel panel-default">
      <div class="panel heading campaign_image center">
        <%= image_tag @campaign.image.url(:medium) %>
      </div>
      <div class="panel-body">
        <h1><%= @campaign.title %> </h1>
        <p><%= @campaign.description %></p>
      </div>
      <div class="panel-footer">
        <div class="row">
          <div class="col-md-6">
            <div id="user">
              <p> Post by <%= @campaign.user.email %></p>
            </div>
          </div>
          <div class="col md-6">
            <div class="btn-group pull-right">
              <% if user_signed_in? %>
                <%= link_to "Edit", edit_campaign_path, class: "btn btn-info" %>
                <%= link_to "Delete", campaign_path, method: :delete, data: { confirm: "Are you sure?"}, class: "btn btn-danger" %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AD CREW</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="nav navbar navbar-inverse">
      <div class="container">
        <div class="navbar-brand" style="display: flex; justify-content: space-between;">
          <%= link_to "Insta", root_path %>
          <% if user_signed_in? %>
            <ul class="nav navbar navbar-left" style="display: flex; justify-content: end;">
              <li><%= link_to "Gram It!", new_campaign_path %></li>
              <li><%= link_to "Settings", edit_user_registration_path %></li>
              <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
            </ul>
          <% else %>
            <ul class="nav navbar navbar-left">
              <li> <%= link_to "Log In", new_user_session_path %> </li>
          <% end %>
            </ul>
        </div>
      </div>
    </div>
    <div class="container">
    <%# <%= flash.each do |name, msg| %>
      <%# <%= content_tag :div, msg, class: "alert alert-in" %>
    <%# <% end %>
    <%= yield %>
    </div>
  </body>
</html>